# ===================================================================
# Grafana provisioning - datasource apne aap configure ho jayega
# (Grafana UI me manually add nahi karna padega)
# ===================================================================
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
